backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /public/images
publish_mode: editorial_workflow

collections:
  - name: "testimonial"
    label: "Testimonial"
    folder: "src/pages"
    fields:
      - {label: "Review", name: "review", widget: "string", default: "default-comment"}
      - {label: "Rating", name: "rating", widget: "string"}
      # - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Description", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      # - {label: "Featured Image", name: "featuredimage", widget: image}
      # - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Tags", name: "tags", widget: "list"}
